name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.19.x
          cache: npm
      - name: Install dependencies (workspaces)
        run: npm ci
      - name: Lint frontend
        run: npm run lint -w apps/frontend
      - name: Test frontend
        run: npm run test:run -w apps/frontend
      - name: Generate Prisma client
        run: npm run prisma:generate -w apps/server
      - name: Build frontend
        run: npm run build -w apps/frontend
      - name: Build server
        run: npm run build -w apps/server
